# ########################################################################### #
# Deployment Tags, select which services you would like to deploy
# ########################################################################### #
tags:
# Tag eric-dp-common install the below  base services that are required.
  eric-dp-common: false
  # Individual services disabled but could be installed separately.
  eric-data-document-database-pg: false
  eric-pm-server: false
  eric-log-shipper: false
  eric-data-search-engine: false
  eric-data-search-engine-curator: false
  eric-log-transformer: false
  eric-ctrl-bro: false
  eric-cnom-server: false
  eric-cnom-document-database-mg: false
  #eric-tm-ingress-controller-cr: false
  eric-enmsg-gossiprouter-eap7: false
  eric-enmsg-gossiprouter-cache: false
  eric-enm-sfwkdb-schemamgt: false
  eric-oss-monitoring: false
# Tag eric-enmsg-dpmediation installs dp mediation deployment
  eric-enmsg-dpmediation: false


# ########################################################################### #
# global settings.
# ########################################################################### #
global:
  replicas-eric-enmsg-dpmediation: 2
  # Disable service to service tls support in ADP.
  security:
    tls:
      enabled: false
  registry:
    url: armdocker.rnd.ericsson.se
    pullSecret:
  timezone: UTC


# Enabled collection of kulelet metrics.
  cadvisormetrics:
    enabled: true
  kubelet:
    enabled: true

# ########################################################################### #
# Over ride service defaults.
# ########################################################################### #
eric-data-document-database-pg:
  nameOverride: "postgres"
  brAgent:
    enabled: true
    logicalDBBackupEnable: true
    backupTypeList:
    - "configuration-data"
    backupDataModelConfig: eric-enmsg-dpmediation-pg-brm-config
  persistentVolumeClaim:
    storageClassName: network-block
    size: 10Gi
  credentials:
    kubernetesSecretName: document-database-pg-secret
  # postgresConfig:
    # autovacuum: "on"
    # autovacuum_analyze_threshold: 2000
    # autovacuum_max_workers: 6
    # autovacuum_naptime: "2min"
    # autovacuum_vacuum_threshold: 4000
    # max_wal_size: "1GB"
    # min_wal_size: "80MB"
    # client_min_messages: "WARNING"
    # effective_cache_size: "10240MB"
    # log_autovacuum_min_duration: 1000
    # log_connections: "off"
    # log_disconnections: "off"
    # log_duration: "off"
    # log_hostname: "off"
    # log_line_prefix: "db=%d,user=%u,%i"
    # log_min_error_statement: "WARNING"
    # log_min_messages: "WARNING"
    # log_rotation_age: 10080
    # log_rotation_size: 102400
    # log_truncate_on_rotation: "on"
    # maintenance_work_mem: "128MB"
    # max_connections: 700
    # max_prepared_transactions: 500
    # max_stack_depth: "4MB"
    # shared_buffers: "4096MB"
    # temp_buffers: "64MB"
    # work_mem: "64MB"
    # log_directory: 'pg_log'
    # log_filename: 'postgresql-%a.log'
    # logging_collector: "on"
  security:
    postgres:
      tls:
        enable: false
    tls:
      brAgent:
        enabled: false
  global:
    security:
      tls:
        enabled: false
  resources:
    postgres:
      requests:
        memory: 4000Mi
        cpu: 1000m
      limits:
        memory: 4000Mi
        cpu: 2000m

# Use defaults set in helm hook.
postgresCredentials:
  superPwd:
  customUser:
  customPwd:

eric-log-shipper:
  nodeSelector: {}
  rbac:
    createServiceAccount: true
  logshipper:
    cfgData: ""
    autodiscover:
      enabled: true
      namespace: ".RELEASE.NAMESPACE"
      logplane: adp-app-logs
  additionalVolumes: |
    - name: dockervol
      hostPath:
        path: /var/lib/docker
  additionalVolumeMounts: |
    - name: dockervol
      mountPath: /var/lib/docker
  resources:
    logshipper:
      limits:
        memory: 2Gi
        cpu: 500m
      requests:
        memory: 2Gi
        cpu: 300m

eric-log-transformer:
  nodeSelector: {}
  config:
    adpJson:
      transformation:
        enabled: true
  syslog:
    syslogLogplane: adp-app-logs
  searchengine:
    logplaneConfig:
      - field: "[facility]"
        value: "log audit"
        newLogplane: "adp-app-audit-logs"
      - field: "[severity]"
        value: "debug"
        newLogplane: "adp-app-debug-logs"
      - field: "[extra_data][asi][log_plane]"
        value: "alarm"
        newLogplane: "adp-app-asi-logs"
      - field: "[facility]"
        value: "security/authorization messages"
        newLogplane: "adp-app-security-logs"
  # 1 replica observed to be low performance in our deployment
  replicaCount: 2

eric-data-search-engine:
  enabled: true
  nameOverride: "elasticsearch"
  jvmHeap:
    ingest: "1024m"
    master: "512m"
    data: "1024m"
  resources:
    ingest:
      limits:
        cpu: "500m"
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "2Gi"
    # master:
      # limits:
        # cpu: "500m"
        # memory: "2Gi"
      # requests:
        # cpu: "500m"
        # memory: "2Gi"
    # data:
      # limits:
        # cpu: "1000m"
        # memory: "8Gi"
      # requests:
        # cpu: "1000m"
        # memory: "8Gi"
  persistence:
    data:
      persistentVolumeClaim:
        storageClassName: network-block
        size: "10Gi"
    backup:
      persistentVolumeClaim:
        size: "10Gi"
        storageClassName: network-file 
  brAgent:
    enabled: false
    cleanRestore: true
    backupRepository:
      type: "fs"
  global:
    security:
      tls:
        enabled: false


eric-data-search-engine-curator:
  enabled: true
  cronjob:
    curator:
      enabled: true
      schedule: "0 */1 * * *"
      successfulJobHistoryLimit: 3
      failedJobHistoryLimit: 5
  searchengine:
    host: elasticsearch
    port: 9200

  actions: |
    1:
      action: delete_indices
      description: Remove logs older than 7 days
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_logs-application-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 7
    2:
      action: delete_indices
      description: Remove logs when over 45 GB of space is used
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_logs-application-
      - filtertype: space
        disk_space: 45
        use_age: True
        source: creation_date
    3:
      action: delete_indices
      description: Remove WARN level and above logs older than 30 days
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_warn_and_above_logs_index-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 30
    4:
      action: delete_indices
      description: Remove ADP logs older than 30 days
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_adp_logs_index-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 30
    5:
      action: delete_indices
      description: Remove INFO level and lower logs older than 7 days
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_info_logs_index-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 7
    6:
      action: delete_indices
      description: Remove opendj AUDIT logs older than 7 days
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_opendj_audit_logs_index-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 7
    7:
      action: delete_indices
      description: Remove AUDIT logs older than 90 days
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_audit_logs_index-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 90
    8:
      action: delete_indices
      description: Remove INFO level logs when over 90 GB of space is used
      options:
        disable_action: false
        ignore_empty_list: true
      filters:
      - filtertype: pattern
        kind: prefix
        value: enm_info_logs_index-
      - filtertype: space
        disk_space: 90
        use_age: True
        source: creation_date


eric-ctrl-bro:
  nodeSelector: {}
  persistence:
    persistentVolumeClaim:
      storageClassName: network-block
  #security:
  #  tls:
  #    broToAgent:
  #      enabled: true


eric-cnom-document-database-mg:
  nodeSelector: {}
  persistence:
    storageClass: network-block
  loggingAudit:
    - stdout

eric-cnom-server:
  nodeSelector: {} 
  dashboards:
    configMap: "dp-dashboards"
  searchEngine:
    host: "elasticsearch"
  service:
    # Service type of the CNOM service
    type: LoadBalancer                    
  authentication:
    enabled: false
  features:
    alarmViewer: false


eric-pm-server:
  enabled: true
  global:
    security:
      tls:
        enabled: false
  rbac:
    appMonitoring:
      enabled: false
      configFileCreate: false
  server:
    serviceAccountName: eric-domain-proxy-standalone-pm-server
  serverFiles:
    prometheus.yml: |
      global:
        scrape_interval: 60s
        scrape_timeout: 10s
        evaluation_interval: 1m
      rule_files:
        - "/etc/config/recording_rules.yml"
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
              - localhost:9090
              - localhost:9087
        {{- if .Values.global.kubelet.enabled }}
        - job_name: 'kubelet'

          scheme: https

          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token


          kubernetes_sd_configs:
            - role: node
              namespaces:
                names:
                - {{ .Release.Namespace }}
          relabel_configs:
            - source_labels: [__address__]
              target_label: instance
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__metrics_path__]
              target_label: metrics_path
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics
            - replacement: https-metrics
              target_label: endpoint
            - replacement: eric-enm-kubelet
              target_label: service
            - source_labels: [__meta_kubernetes_node_label_kubernetes_io_hostname]
              target_label: node
        {{- end }}
        {{- if .Values.global.cadvisormetrics.enabled }}
        - job_name: 'kubelet-cadvisor'

          scheme: https

          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

          kubernetes_sd_configs:
            - role: node
              namespaces:
                names:
                - {{ .Release.Namespace }}
          metrics_path: /metrics/cadvisor
          relabel_configs:
            - source_labels: [__address__]
              target_label: instance
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__metrics_path__]
              target_label: metrics_path
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
            - replacement: https-metrics
              target_label: endpoint
            - source_labels: [__meta_kubernetes_node_label_kubernetes_io_hostname]
              target_label: node
            - replacement: eric-enm-kubelet
              target_label: service
        {{- end }}
        # Scrape config for service endpoints.
        #
        # The relabeling allows the actual service scrape endpoint to be configured
        # via the following annotations:
        #
        # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
        # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
        # to set this to `https` & most likely set the `tls_config` of the scrape config.
        # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
        # * `prometheus.io/port`: If the metrics are exposed on a different port to the
        # service then set this appropriately.

        - job_name: 'kubernetes-service-endpoints'

          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                - {{ .Release.Namespace }}
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: job
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: ((?:\[.+\])|(?:.+))(?::\d+);(\d+)
              replacement: $1:$2
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: service
            - replacement: metrics
              target_label: endpoint
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_service_annotation_isnodeexporter]
              regex: 'true'
              action: drop
            - source_labels: [__meta_kubernetes_service_label_app]
              regex: (.+)
              action: replace
              target_label: app
            - source_labels: [__meta_kubernetes_service_label_sgname]
              regex: (.+)
              action: replace
              target_label: sgname

      remote_write:
      - url: http://remotewriter:1234/receive
        remote_timeout: 30s
              
eric-enm-monitoring-master:
  enmdeploy: false
  monitoring:
    autoUpload:
      enabled: true
      ddpsite:
      account:
      password:
    envVars:
      PROMETHEUS_SVC: eric-pm-server
