apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}-logging
  labels:
{{ include "eric-ctrl-bro.k8sLabels" . | indent 4 }}
{{- include "eric-ctrl-bro.prodInfoLabels" . | indent 4}}
  annotations:
{{ include "eric-ctrl-bro.prodInfoAnnotations" . | indent 4 }}
data:
  {{ .Values.bro.logging.log4j2File }}: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="{{ include "eric-ctrl-bro.log.log4j2Level" . }}" monitorInterval="5">
      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{YYYY-MM-dd'T'HH:mm:ss.sssXXX} %p %c{1}: %m%n"/>
          <RegexFilter regex=".*(Error reading request, ignored|Error running socket processor|JSSE TLS 1.3|Encryptor config not found).*" onMatch="DENY" onMismatch="ACCEPT"/>
        </Console>
      </Appenders>
      <Loggers>
        <Logger name="com.ericsson.adp.mgmt.backupandrestore" level="{{ include "eric-ctrl-bro.log.level" . }}">
        </Logger>
        <Root level="{{ include "eric-ctrl-bro.log.rootLevel" . }}">
          {{- with . }}
          {{- $logstreaming := include "eric-ctrl-bro.logstreaming" . | fromYaml }}
          {{- if has "console" (get $logstreaming "logOutput") }}
          <AppenderRef ref="Console"/>
          {{- end }}
          {{- end }}
        </Root>
      </Loggers>
    </Configuration>
