{{- $g := fromJson (include "eric-pm-server.global" .) -}}
{{- if and $g.security.tls.enabled  (not .Values.service.endpoints.reverseproxy.tls.certificateAuthorityBackwardCompatibility) }}
apiVersion: siptls.sec.ericsson.com/v1alpha1
kind: InternalUserCA
metadata:
  name: {{ template "eric-pm-server.name" . }}-query-ca
  annotations:
{{- include "eric-pm-server.helm-annotations" . | indent 2 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-pm-server.name" . }}
    app.kubernetes.io/version: {{ template "eric-pm-server.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "eric-pm-server.name" . }}
    chart: {{ template "eric-pm-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  kubernetes:
    generatedSecretName: "eric-pm-server-query-ca"
    certificateName: "query-cacertbundle.pem"

  certificate:
    subject:
      cn: {{ template "eric-pm-server.name" . }}
{{- end }}
