{{- $g := fromJson (include "eric-pm-server.global" .) -}}
{{- if $g.security.tls.enabled }}
apiVersion: siptls.sec.ericsson.com/v1alpha1
kind: InternalCertificate
metadata:
  name: {{ template "eric-pm-server.name" . }}-int-rw-client-cert
  annotations:
{{- include "eric-pm-server.helm-annotations" . | indent 2 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-pm-server.name" . }}
    app.kubernetes.io/version: {{ template "eric-pm-server.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "eric-pm-server.name" . }}
    chart: {{ template "eric-pm-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:

  kubernetes:
    generatedSecretName: {{ template "eric-pm-server.name" . }}-int-rw-client-cert
    certificateName: "clicert.pem"
    privateKeyName: "cliprivkey.pem"
  certificate:
    subject:
      cn: {{ template "eric-pm-server.name" . }}
    issuer:
      reference: {{ template "eric-pm-server.name" . }}-int-rw-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}
