apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-pm-server.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "eric-pm-server.name" . }}
    app.kubernetes.io/version: {{ template "eric-pm-server.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "eric-pm-server.name" . }}
    chart: {{ template "eric-pm-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: {{ include "eric-pm-server.helm-annotations" . | nindent 2 }}
spec:
  minAvailable: {{ int .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "eric-pm-server.name" . }}
