{{- if .Values.rbac.appMonitoring.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
{{- include "eric-pm-server.helm-annotations" . | indent 2 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-pm-server.name" . }}
    app.kubernetes.io/version: {{ template "eric-pm-server.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "eric-pm-server.name" . }}
    chart: {{ template "eric-pm-server.chart" . }}
    component: {{ .Values.server.name | quote }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "eric-pm-server.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-pm-server.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "eric-pm-server.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
