{{- if .Values.rbac.appMonitoring.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
{{- include "eric-pm-server.helm-annotations" . | indent 2 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-pm-server.name" . }}
    app.kubernetes.io/version: {{ template "eric-pm-server.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "eric-pm-server.name" . }}
    chart: {{ template "eric-pm-server.chart" . }}
    component: {{ .Values.server.name | quote }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "eric-pm-server.name" . }}
{{- end }}
