{{- $g := fromJson (include "eric-pm-server.global" .) -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
{{- include "eric-pm-server.helm-annotations" . | indent 2 }}
{{- if .Values.server.service.annotations }}
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "eric-pm-server.name" . }}
    app.kubernetes.io/version: {{ template "eric-pm-server.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "eric-pm-server.name" . }}
    chart: {{ template "eric-pm-server.chart" . }}
    component: {{ .Values.server.name | quote }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
  name: {{ template "eric-pm-server.name" . }}
spec:
{{- if $g.internalIPFamily }}
  ipFamilies: [{{ $g.internalIPFamily | quote }}]  # ipFamilies was introduced in K8s v1.20
{{- end }}
  ports:
    {{- if or (and $g.security.tls.enabled (eq .Values.service.endpoints.reverseproxy.tls.enforced "optional")) (not $g.security.tls.enabled) }}
    - name: http
      protocol: TCP
      port: 9090
    {{- end }}
    {{- if $g.security.tls.enabled }}
    - name: https
      protocol: TCP
      port: 9089
    {{- end }}
  selector:
    app: {{ template "eric-pm-server.name" . }}
    component: {{ .Values.server.name | quote }}
    release: {{ .Release.Name }}
  type: ClusterIP
