# Default values for log.
# This is a YAML-formatted file.
affinity:
  podAntiAffinity: "soft"

replicaCount: 1

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25% # Kubernetes default value
    maxSurge: 25% # Kubernetes default value

tolerations: []

#global:
#  registry:
#    imagePullPolicy: "IfNotPresent"
#    url: "armdocker.rnd.ericsson.se"
#  timezone: "UTC"
#  nodeSelector: {}
#  pullSecret:
#  internalIPFamily:
#  security:
#    tls:
#      enabled: true
#    policyBinding:
#      create: false
#    policyReferenceMap:
#      default-restricted-security-policy: "default-restricted-security-policy"

annotations: {}

labels: {}

imageCredentials:
  repoPath: "proj-adp-log-released"
  registry:
    imagePullPolicy: # When set this overrides global image pull policy
    url:
  pullSecret: # When set this overrides global pull secret
  logshipper:
    registry:
      url:
      imagePullPolicy:
    repoPath: "proj-bssf/adp-log/release"
images:
  logtransformer:
    name: "eric-log-transformer"
    tag: "5.6.0-27"
  metrics:
    name: "eric-log-transformer-pm-metrics"
    tag: "5.6.0-27"
  tlsproxy:
    name: "eric-log-transformer-tls-proxy"
    tag: "5.6.0-27"
  logshipper:
    name: "eric-log-shipper"
    tag: "5.3.0-14"

service:
  portApi: 9600
  endpoints:
    syslogIn:
      tls:
        enforced: "required"
    filebeat:
      tls:
        enforced: "required"
    jsonIn:
      tls:
        enforced: "required"

livenessProbe:
  initialDelaySeconds: 600
  timeoutSeconds: 15
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  metrics:
    initialDelaySeconds: 600
    timeoutSeconds: 15
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
  tlsproxy:
    initialDelaySeconds: 5
    timeoutSeconds: 15
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  logshipper:
    initialDelaySeconds: 300
    timeoutSeconds: 15
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 15
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  metrics:
    initialDelaySeconds: 10
    timeoutSeconds: 15
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
  logshipper:
    initialDelaySeconds: 30
    timeoutSeconds: 15
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3

searchengine:
  host: eric-data-search-engine
  port: 9200
  logplaneConfig:
  - field: "[extra_data][asi][log_plane]"
    value: "alarm"
    newLogplane: "adp-app-asi-logs"
  - field: "[facility]"
    value: "log audit"
    newLogplane: "adp-app-audit-logs"
  exclusion:
  - logplane:
    rules:
      - field:
        value:

log:
  # Supported values ["stdout", "stream"]
  outputs: ["stdout"]
  logshipper:
    level: info
  logplane:
    default: "adp-app-logs"
    logtransformer: ""
    metrics: ""
    tlsproxy: ""

jvmHeap: 1024m

resources:
  logtransformer:
    requests:
      cpu: 250m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  metrics:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "25m"
      memory: "64Mi"
  tlsproxy:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "25m"
      memory: "64Mi"
  logshipper:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "100Mi"
      cpu: "100m"

networkPolicy:
  egress:
  #  - cidr: 172.17.0.0/32
  #    ports:
  #    - protocol: TCP
  #      port: 1234
  #    - protocol: UDP
  #      port: 2345

json:
  logplane: "adp-app-logs"

syslog:
 syslogLogplane: adp-app-logs

egress:
  lumberjack:
    enabled: false
    remoteHosts:
      #- id: my_lbjk_id1
      #  host: hostname1.ericsson.se
      #  port: 9991
      #  codec: json
      #- id: my_lbjk_id2
      #  host: hostname2.ericsson.se
      #  port: 9992
      #  codec: json
    certificates:
      asymmetricKeyCertificateName: log-lumberjack-client
  syslog:
    enabled: false
    defaultFacility: 1
    defaultSeverity: 5
    tls:
      enabled: true
    certificates:
      asymmetricKeyCertificateName: log-syslog-client
      trustedCertificateListName: log-syslog-client
    remoteHosts: []
    inclusions: []
    exclusions: []
    filter: ""

logLevel: "info"

config:
  adpJson:
    validation:
      enabled: false
    transformation:
      enabled: false
    # Do not add quotes around the field name
    decodedAdpJsonField: json
  filebeat:
    input:
      filter: #|
  fileOutput: false
  filter: #|
  input: #|
  output:
  #  - name: "remote_elastic"
  #    output: |
  #      elasticsearch {
  #        hosts => ["${ELASTICSEARCH_REMOTE_HOSTS}"]
  #        index => "%{logplane}-%{+YYYY.MM.dd}"
  #      }
  #    filter: |
  #      if( [field] != "value" ) {
  #        drop{}
  #      }

metrics:
  enabled: true

clusterDomain: "cluster.local"

podDisruptionBudget:
  maxUnavailable: 1

queue:
  sizePerPipeline: 1024
