{{- if .Values.podDisruptionBudget -}}
{{- if .Values.podDisruptionBudget.maxUnavailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eric-log-transformer.fullname" . }}-pdb
  labels:
{{- include "eric-log-transformer.labels" . | indent 4 }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ include "eric-log-transformer.fullname" . | quote }}
    chart: {{ include "eric-log-transformer.chart" . | quote }}
  annotations:
    {{- include "eric-log-transformer.annotations" . | indent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ include "eric-log-transformer.fullname" . | quote }}
{{- end }}
{{- end }}
