{{ $root := .}}
{{- $name := .Values.service.name  -}}
{{- $instance := .Release.Name  -}}
{{- $version := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{ range $path, $bytes :=  .Files.Glob  "appconfig/configmaps/*.yaml" }}
{{ $name := base ($path) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $instance }}
    app.kubernetes.io/version: {{ $version }}
  name:  {{ $instance }}-{{- template "eric-enmsg-dpmediation.configmapName" (list $name) -}}
data:
{{ tpl ($root.Files.Get $path) $root | indent 2 }}
---
{{ end }}