{{ if or (index .Values "tags" "eric-data-document-database-pg") (index .Values "tags" "eric-dp-common") }}
apiVersion: v1
kind: Secret
metadata:
  name: document-database-pg-secret
  labels:

type: Opaque
data:
  # For custom user
  {{- if .Values.postgresCredentials.customUser }}
  custom-user: {{ .Values.postgresCredentials.customUser | b64enc | quote }}
  {{- else }}
  custom-user: {{ "custom-postgres" | b64enc | quote }}
  {{- end }}

  # For custom user password
  {{- if .Values.postgresCredentials.customPwd }}
  custom-pwd: {{ .Values.postgresCredentials.customPwd | b64enc | quote }}
  {{- else }}
  custom-pwd: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  # For super user and password
  super-user: {{ "postgres" | b64enc | quote }}
  {{- if .Values.postgresCredentials.superPwd }}
  super-pwd: {{ .Values.postgresCredentials.superPwd | b64enc | quote }}
  {{- else }}
  super-pwd: {{ "UDBzdGdyZVNRTDEx" | quote }}
  {{- end }}

  # For metrics user and password
  metrics-user: {{ "exporter" | b64enc | quote }}
  metrics-pwd: {{ "ZXhwb3J0ZXI=" | quote }}

  # For replication user and password
  replica-user: {{ "replica" | b64enc | quote }}
  replica-pwd: {{ "cmVwbGljYQ==" | quote }}
{{- end }}
