{{- if .Values.monitoring.autoUpload.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.jobs.delta.name }}
  labels:
{{- include "eric-enm-monitoring-master.labels" . | indent 4 }}
  annotations:
{{- include "eric-enm-monitoring-master.product-info" . | indent 4 }}
spec:
  concurrencyPolicy: {{ .Values.jobs.delta.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.jobs.delta.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
      {{- include "eric-enm-monitoring-master.labels" . | indent 12 }}
          annotations:
      {{- include "eric-enm-monitoring-master.product-info" . | indent 12 }}
        spec:
          {{- if include "eric-enm-monitoring-master.pullSecrets" . }}
          imagePullSecrets:
            - name: {{ template "eric-enm-monitoring-master.pullSecrets" . }}
          {{- end }}
          containers:
          - image: {{ template "eric-enm-monitoring-master.registryUrl" . }}/{{ .Values.imageCredentials.repoPath }}/{{ index .Values "images" "eric-enm-monitoring-master" "name" }}:{{ index .Values "images" "eric-enm-monitoring-master" "tag" }}
            imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
            name: {{ .Values.jobs.delta.name }}
            env:
              - name: TZ
                value: {{ .Values.global.timezone }}
{{- if .Values.monitoring.envVars }}
{{- range $key, $value := .Values.monitoring.envVars}}
              - name: {{ $key }}
                value: {{ $value }}
{{- end }}
{{- end }}
{{- if .Values.jobs.delta.command }}
            command: {{ .Values.jobs.delta.command }}
{{- end }}
{{- with .Values.jobs.delta.args }}
            args:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.jobs.delta.resources }}
            resources:
{{ toYaml . | indent 14 }}
{{- end }}
{{- with .Values.jobs.delta.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.jobs.delta.secretVolumeMounts }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- if .Values.enmdeploy }}
{{- with .Values.jobs.start.enmVolumeMounts }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end }}
{{- with .Values.jobs.delta.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.jobs.delta.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.jobs.delta.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
{{- end }}
          restartPolicy: {{ .Values.jobs.delta.restartPolicy }}
          serviceAccountName: {{ .Values.serviceAccount }}
{{- with .Values.jobs.delta.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.jobs.delta.secretVolumes }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- if .Values.enmdeploy }}
{{- with .Values.jobs.start.enmVolumes }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end }}
  schedule: {{ .Values.jobs.delta.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.jobs.delta.successfulJobsHistoryLimit }}
{{- end }}
