apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ddc-{{ .Release.Namespace }}
rules:
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - ingresses
  - configmaps
  - secrets
  - persistentvolumeclaims
  - persistentvolumes
  - events
  - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
