apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddcdata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.rwx.ddcdataSize }}
  storageClassName: {{ .Values.global.rwx.storageClass | quote }}
