{{- if .Values.monitoring.autoUpload.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-upload-secret
stringData:
  ddpsite: {{ default "" .Values.monitoring.autoUpload.ddpsite | quote }}
  account: {{ default "" .Values.monitoring.autoUpload.account | quote }}
  password: {{ default "" .Values.monitoring.autoUpload.password | quote }}
{{- end }}
