apiVersion: v1
kind: ConfigMap
metadata:
  name: key{{ .Values.job.name }}
  labels:
    app: {{ .Values.job.name }}
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: "{{ .Values.job.name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: {{ template "eric-enm-sfwkdb-schemamgt.chart" . }}
  annotations:
  {{- include "eric-enm-sfwkdb-schemamgt.product-info" . | indent 4 }}
data:
  postgresql01_passkey: |
    5EacabwlanIHjZ8XAkoPIA== 
