apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-cnom-server.fullname" . }}
  labels:
    {{- include "eric-cnom-server.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cnom-server.product-info" . | nindent 4 }}
    {{- if .Values.annotations }}
    {{- .Values.annotations | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.dashboards.import }}
data:
{{- range $key, $value := .Values.dashboards.import }}
  {{ $key }}.json: {{ quote $value }}
{{- end }}
{{- else }}
data:
  {}
{{- end }}
