apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eric-cnom-server.fullname" . }}
  labels:
    {{- include "eric-cnom-server.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cnom-server.product-info" . | nindent 4 }}
    {{- if .Values.annotations }}
    {{- .Values.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | quote }}
  selector:
    matchLabels:
      {{- include "eric-cnom-server.selectorLabels" . | nindent 6 }}
