{{- $g := fromJson (include "eric-data-search-engine.global" . ) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "eric-data-search-engine.fullname" . }}-discovery
  {{- include "eric-data-search-engine.helm-labels" . | indent 2 }}
  annotations:
  {{- include "eric-data-search-engine.annotations" . | indent 4 }}
  {{- if and (.Values.metrics.enabled) $g.security.tls.enabled }}
    prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
    prometheus.io/port: "9115"
    prometheus.io/scheme: "https"
  {{- end }}
spec:
  {{- if $g.internalIPFamily }}
    {{- if semverCompare "<1.16" .Capabilities.KubeVersion.GitVersion }}
      {{- printf "Specifying global.internalIPFamily is only supported for deployment in Kubernetes clusters with version 1.16 or higher." | fail }}
    {{- end }}
  ipFamily: {{ $g.internalIPFamily | quote }}
  {{- end }}
  publishNotReadyAddresses: true
  selector:
    app: {{ include "eric-data-search-engine.fullname" . | quote }}
    component: eric-data-search-engine
    role: master
  type: ClusterIP
  ports:
  - name: transport
    port: {{ .Values.master.tcpPort }}
    protocol: TCP
  {{- if .Values.metrics.enabled }}
  {{- if $g.security.tls.enabled }}
  - name: metrics-tls
    port: 9114
    targetPort: 9115
    protocol: TCP
  {{- else }}
  - name: metrics
    port: {{ .Values.metrics.httpPort }}
    protocol: TCP
  {{- end }}
  {{- end }}